# import turtle
# swati=turtle.Turtle()
# swati.speed(1)
# swati.forward(100)
# swati.left(90)
# swati.forward(200)
# swati.left(90)
# swati.forward(100)
# swati.left(90)
# swati.forward(200)

# Pattern2
# import turtle
# pen=turtle.Turtle()
# pen.speed(1)
# pen.color("blue", "black")    #this will set the color
# pen.begin_fill()
# pen.right(90)
# pen.forward(100)
# pen.left(90)
# pen.backward(100)
# pen.left(30)
# pen.forward(100)
# pen.right(45)
# pen.backward(100)
# pen.left(28)
# pen.forward(120)
# pen.end_fill()

# #Fill the color
# import turtle
# pencile=turtle.Turtle()
# pencile.speed(1)
# pencile.color("black","cyan")
# pencile.begin_fill()
# pencile.forward(100)
# pencile.left(90)
# pencile.forward(100)
# pencile.left(90)
# pencile.forward(100)
# pencile.left(90)
# pencile.forward(100)
 

# pencile.forward(200)
# pencile.left(90)
# pencile.forward(100)
# pencile.left(90)
# pencile.forward(100)
# pencile.left(90)
# pencile.forward(100)


# pencile.forward(200)
# pencile.left(45)
# pencile.backward(100)
# pencile.right(45)
# pencile.forward(100)
# pencile.end_fill()

# pencile.done()

# Problem-
import turtle
swati=turtle.Turtle()
swati.color("black","blue")
swati.begin_fill()
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)


swati.penup()
swati.forward(10)
swati.pendown()
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)

swati.penup()
swati.forward(10)

swati.pendown()
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)

swati.penup()
swati.forward(10)

swati.pendown()
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)

swati.penup()
swati.forward(10)

swati.pendown()
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)

swati.pendown()
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.penup()
swati.forward(10)

swati.pendown()
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)
swati.left(90)
swati.forward(100)

swati.end_fill()
